// Main
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_EXPAND = 'TOGGLE_EXPAND'
export const UPDATE_INPUT_FIELD = 'UPDATE_INPUT_FIELD'
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'

// Login
export const UPDATE_LOGIN_FIELD = 'UPDATE_LOGIN_FIELD'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER_DETAILS = 'SET_USER_DETAILS'

// Web UI Actions
export const TOGGLE_LOADER_FIELD = 'TOGGLE_LOADER_FIELD'

// User
export const UPDATE_USER_FIELD = 'UPDATE_USER_FIELD'
export const SET_USER_LIST = 'SET_USER_LIST'
export const REMOVE_USER = 'REMOVE_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const SET_USER_PACKAGE_LIST = 'SET_USER_PACKAGE_LIST'
export const SET_EDIT_USER = 'SET_EDIT_USER'
export const SET_CURRENT_USER_LIST = 'SET_CURRENT_USER_LIST'
export const UPDATE_USER = 'UPDATE_USER'

