// Main
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_EXPAND = 'TOGGLE_EXPAND'
export const UPDATE_INPUT_FIELD = 'UPDATE_INPUT_FIELD'
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'

// Login
export const UPDATE_LOGIN_FIELD = 'UPDATE_LOGIN_FIELD'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER_DETAILS = 'SET_USER_DETAILS'

// Web UI Actions
export const TOGGLE_LOADER_FIELD = 'TOGGLE_LOADER_FIELD'

// Trainee
export const UPDATE_USER_FIELD = 'UPDATE_USER_FIELD'
export const SET_USER_LIST = 'SET_USER_LIST'
export const REMOVE_USER = 'REMOVE_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const SET_USER_PACKAGE_LIST = 'SET_USER_PACKAGE_LIST'
export const SET_EDIT_USER = 'SET_EDIT_USER'
export const SET_CURRENT_USER_LIST = 'SET_CURRENT_USER_LIST'

// Training Package
export const UPDATE_TRAINING_PACKAGE_FIELD = 'UPDATE_TRAINING_PACKAGE_FIELD'
export const SET_TRAINING_PACKAGE_LIST = 'SET_TRAINING_PACKAGE_LIST'
export const REMOVE_TRAINING_PACKAGE = 'REMOVE_TRAINING_PACKAGE'
export const SET_CURRENT_TRAINING_PACKAGE = 'SET_CURRENT_TRAINING_PACKAGE'
export const SET_USER_TRAININGPACKAGE_LIST ='SET_USER_TRAININGPACKAGE_LIST'

// Goal
export const UPDATE_GOAL_FIELD = 'UPDATE_GOAL_FIELD'
export const SET_GOAL_LIST = 'SET_GOAL_LIST'
export const REMOVE_GOAL = 'REMOVE_GOAL'
export const SET_CURRENT_GOAL = 'SET_CURRENT_GOAL'
export const SET_USER_GOAL_LIST = 'SET_USER_GOAL_LIST'

// Location
export const UPDATE_LOCATION_FIELD = 'UPDATE_LOCATION_FIELD'
export const SET_LOCATION_LIST = 'SET_LOCATION_LIST'
export const REMOVE_LOCATION = 'REMOVE_LOCATION'
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'

// Expense
export const UPDATE_EXPENSE_FIELD = 'UPDATE_EXPENSE_FIELD'
export const SET_EXPENSE_LIST = 'SET_EXPENSE_LIST'
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE'
export const SET_CURRENT_EXPENSE = 'SET_CURRENT_EXPENSE'

// Home Session
export const UPDATE_HOME_SESSION_FIELD = 'UPDATE_HOME_SESSION_FIELD'
export const SET_HOME_SESSION_LIST = 'SET_HOME_SESSION_LIST'
export const REMOVE_HOME_SESSION = 'REMOVE_HOME_SESSION'
export const SET_CURRENT_HOME_SESSION = 'SET_CURRENT_HOME_SESSION'
export const SET_USER_HOMESESSION_LIST ='SET_USER_HOMESESSION_LIST'

// Session Name
export const UPDATE_SESSION_NAME_FIELD = 'UPDATE_SESSION_NAME_FIELD'
export const SET_SESSION_NAME_LIST = 'SET_SESSION_NAME_LIST'
export const REMOVE_SESSION_NAME = 'REMOVE_SESSION_NAME'
export const SET_CURRENT_SESSION_NAME = 'SET_CURRENT_SESSION_NAME'
export const SET_USER_SESSIONNAME_LIST ='SET_USER_SESSIONNAME_LIST'

// Session
export const UPDATE_SESSION_FIELD = 'UPDATE_SESSION_FIELD'
export const SET_SESSION_LIST = 'SET_SESSION_LIST'
export const REMOVE_SESSION = 'REMOVE_SESSION'
export const SET_CURRENT_SESSION = 'SET_CURRENT_SESSION'
export const SET_SESSION_TYPE = 'SET_SESSION_TYPE'
export const SET_USER_SESSION_LIST = 'SET_USER_SESSION_LIST'

// Diet
export const UPDATE_DIET_FIELD = 'UPDATE_DIET_FIELD'
export const SET_DIET_MAP_USER = 'SET_DIET_MAP_USER'
export const SET_DIET_LIST = 'SET_DIET_LIST'
export const REMOVE_DIET = 'REMOVE_DIET'
export const SET_CURRENT_DIET = 'SET_CURRENT_DIET'

// Payment
export const UPDATE_PAYMENT_FIELD = 'UPDATE_PAYMENT_FIELD'
export const SET_PAYMENT_LIST = 'SET_PAYMENT_LIST'
export const REMOVE_PAYMENT = 'REMOVE_PAYMENT'
export const SET_CURRENT_PAYMENT = 'SET_CURRENT_PAYMENT'
export const SET_PAYMENT_MAP = 'SET_PAYMENT_MAP'

// TraineeStatus
export const UPDATE_USER_STATUS_FIELD = 'UPDATE_USER_STATUS_FIELD'
export const SET_USER_STATUS_LIST = 'SET_USER_STATUS_LIST'
export const REMOVE_USER_STATUS = 'REMOVE_USER_STATUS'
export const SET_CURRENT_USER_STATUS = 'SET_CURRENT_USER_STATUS'
export const SET_USER_STATUS_LISTֹ_MAP = 'SET_USER_STATUS_LISTֹ_MAP'

// Exercise
export const UPDATE_EXERCISE_FIELD = 'UPDATE_EXERCISE_FIELD'
export const SET_EXERCISE_LIST = 'SET_EXERCISE_LIST'
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE'

// Scheduled Exercise
export const UPDATE_SCHEDULED_EXERCISE_FIELD = 'UPDATE_SCHEDULED_EXERCISE_FIELD'
export const SET_CURRENT_DAY = 'SET_CURRENT_DAY'
export const SET_SCHEDULED_EXERCISE_LIST = 'SET_SCHEDULED_EXERCISE_LIST'
export const REMOVE_SCHEDULED_EXERCISE = 'REMOVE_SCHEDULED_EXERCISE'
export const SET_SCHEDULED_WEEK = 'SET_SCHEDULED_WEEK'
export const SET_USER_SCHEDULEDEXERCISE_LIST ='SET_USER_SCHEDULEDEXERCISE_LIST'

